- name: appsetup
  include_role:
    name: common
    tasks_from: appsetup.yaml

- name: mavensetup
  include_role:
    name: common
    tasks_from: mavensetup.yaml

- name: systemdsetup
  include_role:
    name: common
    tasks_from: systemdsetup.yaml

- name: install mysql client
  ansible.builtin.package:
    name: mysql
    state: installed

- name: import data
  community.mysql.mysql_db:
    name: all
    login_user: "{{ MYSQL_ROOT_USER }}" 
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_host: "{{ MYSQL_HOST }}"
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name: restart shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
