[mongodb]
mongodb.daws-84s.bond

[redis]
redis.daws-84s.bond

[mysql]
mysql.daws-84s.bond

[rabbitmq]
rabbitmq.daws-84s.bond

[catalogue]
catalogue.daws-84s.bond

[user]
user.daws-84s.bond

[cart]
cart.daws-84s.bond

[shipping]
shipping.daws-84s.bond

[payment]
payment.daws-84s.bond

[frontend]
frontend.daws-84s.bond

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321