
- name: appsetup
  include_role:
    name: common
    tasks_from: appsetup

- name: pythonsetup
  include_role:
    name: common
    tasks_from: pythonsetup

- name: systemdsetup
  include_role:
    name: common
    tasks_from: systemdsetup
